sudo: false

language:
  - php

os:
  - linux

php:
  - nightly
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2

matrix:
  allow_failures:
    - php: nightly
    - os: osx

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - npm install
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox http://localhost:1111/capture &
  - sleep 5
  - phantomjs node_modules/buster/script/phantom.js http://localhost:1111/capture &
  - sleep 5
  - mysql -u root < ./dist-docs/sample_schema_mysql.txt
  - sqlite3 /tmp/sample.sq3 < ./dist-docs/sample_schema_sqlite.txt
  - chmod 666 /tmp/sample.sq3
  - cd INTER-Mediator-UnitTest
  - cat DB_PDO-SQLite_Test.php | sed -e 's/sqlite:\/var\/db\/im\/sample.sq3/sqlite:\/tmp\/sample.sq3/' > DB_PDO-SQLite_Test.tmp; mv DB_PDO-SQLite_Test.tmp DB_PDO-SQLite_Test.php
  - cd ..
  - psql -c 'create database test_db;' -U postgres
  - psql -U postgres -f ./dist-docs/sample_schema_pgsql.txt test_db
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then composer require 'phpunit/phpunit=3.7.x'; composer install; fi"

script:
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.2' ]; then phpunit --configuration ./INTER-Mediator-UnitTest/phpunit.xml ./INTER-Mediator-UnitTest/INTERMediator_AllTests.php; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.2' ]; then vendor/bin/phpunit --configuration ./INTER-Mediator-UnitTest/phpunit.xml ./INTER-Mediator-UnitTest/INTERMediator_AllTests.php; fi"
  - npm test

notifications:
  slack:
    rooms:
      - intermediator:INKkFZQWI94gsq6DYxRnaWeb#product
    on_success: change
    on_failure: always
    on_start: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab3046b24c1b21df358d
